//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subs.XMLServiceTest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authorize", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseModel))]
        Subs.XMLServiceTest.ServiceReference1.AuthorizeResponse Authorize(Subs.XMLServiceTest.ServiceReference1.AuthorizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authorize", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.AuthorizeResponse> AuthorizeAsync(Subs.XMLServiceTest.ServiceReference1.AuthorizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authorizations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseModel))]
        Subs.XMLServiceTest.ServiceReference1.AuthorizationsResponse Authorizations(Subs.XMLServiceTest.ServiceReference1.AuthorizationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authorizations", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.AuthorizationsResponse> AuthorizationsAsync(Subs.XMLServiceTest.ServiceReference1.AuthorizationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindEMailByCustomerId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseModel))]
        Subs.XMLServiceTest.ServiceReference1.FindEMailByCustomerIdResponse FindEMailByCustomerId(Subs.XMLServiceTest.ServiceReference1.FindEMailByCustomerIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindEMailByCustomerId", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.FindEMailByCustomerIdResponse> FindEMailByCustomerIdAsync(Subs.XMLServiceTest.ServiceReference1.FindEMailByCustomerIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindCustomerIdByEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseModel))]
        Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByEmailResponse FindCustomerIdByEmail(Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindCustomerIdByEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByEmailResponse> FindCustomerIdByEmailAsync(Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindCustomerIdByNationalId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseModel))]
        Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByNationalIdResponse FindCustomerIdByNationalId(Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByNationalIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindCustomerIdByNationalId", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByNationalIdResponse> FindCustomerIdByNationalIdAsync(Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByNationalIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseModel))]
        Subs.XMLServiceTest.ServiceReference1.InsertCustomerResponse InsertCustomer(Subs.XMLServiceTest.ServiceReference1.InsertCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.InsertCustomerResponse> InsertCustomerAsync(Subs.XMLServiceTest.ServiceReference1.InsertCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseModel))]
        Subs.XMLServiceTest.ServiceReference1.GetCustomerResponse GetCustomer(Subs.XMLServiceTest.ServiceReference1.GetCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.GetCustomerResponse> GetCustomerAsync(Subs.XMLServiceTest.ServiceReference1.GetCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseModel))]
        Subs.XMLServiceTest.ServiceReference1.UpdateCustomerResponse UpdateCustomer(Subs.XMLServiceTest.ServiceReference1.UpdateCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.UpdateCustomerResponse> UpdateCustomerAsync(Subs.XMLServiceTest.ServiceReference1.UpdateCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertDeliveryAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseModel))]
        Subs.XMLServiceTest.ServiceReference1.InsertDeliveryAddressResponse InsertDeliveryAddress(Subs.XMLServiceTest.ServiceReference1.InsertDeliveryAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertDeliveryAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.InsertDeliveryAddressResponse> InsertDeliveryAddressAsync(Subs.XMLServiceTest.ServiceReference1.InsertDeliveryAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeliveryAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseModel))]
        Subs.XMLServiceTest.ServiceReference1.GetDeliveryAddressResponse GetDeliveryAddress(Subs.XMLServiceTest.ServiceReference1.GetDeliveryAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeliveryAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.GetDeliveryAddressResponse> GetDeliveryAddressAsync(Subs.XMLServiceTest.ServiceReference1.GetDeliveryAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDeliveryAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseModel))]
        Subs.XMLServiceTest.ServiceReference1.UpdateDeliveryAddressResponse UpdateDeliveryAddress(Subs.XMLServiceTest.ServiceReference1.UpdateDeliveryAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDeliveryAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.UpdateDeliveryAddressResponse> UpdateDeliveryAddressAsync(Subs.XMLServiceTest.ServiceReference1.UpdateDeliveryAddressRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthorizationHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string sourceField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DeliveryAddressData2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool completedField;
        
        private int deliveryAddressIdField;
        
        private string phoneNumberField;
        
        private int countryIdField;
        
        private string provinceField;
        
        private string cityField;
        
        private string suburbField;
        
        private string streetField;
        
        private string streetExtensionField;
        
        private string streetSuffixField;
        
        private string streetNoField;
        
        private string buildingField;
        
        private string floorField;
        
        private string roomField;
        
        private string postCodeField;
        
        private string sDIField;
        
        private string modifiedByField;
        
        private System.DateTime modifiedOnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Completed {
            get {
                return this.completedField;
            }
            set {
                this.completedField = value;
                this.RaisePropertyChanged("Completed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int DeliveryAddressId {
            get {
                return this.deliveryAddressIdField;
            }
            set {
                this.deliveryAddressIdField = value;
                this.RaisePropertyChanged("DeliveryAddressId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("PhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int CountryId {
            get {
                return this.countryIdField;
            }
            set {
                this.countryIdField = value;
                this.RaisePropertyChanged("CountryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
                this.RaisePropertyChanged("Province");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Suburb {
            get {
                return this.suburbField;
            }
            set {
                this.suburbField = value;
                this.RaisePropertyChanged("Suburb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string StreetExtension {
            get {
                return this.streetExtensionField;
            }
            set {
                this.streetExtensionField = value;
                this.RaisePropertyChanged("StreetExtension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string StreetSuffix {
            get {
                return this.streetSuffixField;
            }
            set {
                this.streetSuffixField = value;
                this.RaisePropertyChanged("StreetSuffix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string StreetNo {
            get {
                return this.streetNoField;
            }
            set {
                this.streetNoField = value;
                this.RaisePropertyChanged("StreetNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Building {
            get {
                return this.buildingField;
            }
            set {
                this.buildingField = value;
                this.RaisePropertyChanged("Building");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Floor {
            get {
                return this.floorField;
            }
            set {
                this.floorField = value;
                this.RaisePropertyChanged("Floor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Room {
            get {
                return this.roomField;
            }
            set {
                this.roomField = value;
                this.RaisePropertyChanged("Room");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string PostCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
                this.RaisePropertyChanged("PostCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string SDI {
            get {
                return this.sDIField;
            }
            set {
                this.sDIField = value;
                this.RaisePropertyChanged("SDI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
                this.RaisePropertyChanged("ModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public System.DateTime ModifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                this.modifiedOnField = value;
                this.RaisePropertyChanged("ModifiedOn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomerData3))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerData3 : BaseModel {
        
        private int customerIdField;
        
        private string loginEmailField;
        
        private string passwordField;
        
        private int titleIdField;
        
        private string initialsField;
        
        private string firstNameField;
        
        private string surnameField;
        
        private string nationalId1Field;
        
        private string nationalId2Field;
        
        private string nationalId3Field;
        
        private int companyIdField;
        
        private string departmentField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string address3Field;
        
        private string address4Field;
        
        private string address5Field;
        
        private AddressType addressTypeField;
        
        private int postAddressIdField;
        
        private int physicalAddressIdField;
        
        private int countryIdField;
        
        private string phoneNumberField;
        
        private string cellPhoneNumberField;
        
        private string faxPhoneNumberField;
        
        private string emailAddressField;
        
        private string invoiceEmailField;
        
        private string statementEmailField;
        
        private int correspondence2Field;
        
        private decimal liabilityField;
        
        private System.Nullable<System.DateTime> verificationDateField;
        
        private CustomerStatus statusField;
        
        private string councilNumberField;
        
        private string practiceNumber1Field;
        
        private string practiceNumber2Field;
        
        private string practiceNumber3Field;
        
        private string modifiedByField;
        
        private int checkpointPaymentTransactionIdField;
        
        private System.DateTime checkpointPaymentDateField;
        
        private decimal checkpointPaymentValueField;
        
        private System.DateTime checkpointInvoiceDateField;
        
        private System.DateTime modifiedOnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("CustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LoginEmail {
            get {
                return this.loginEmailField;
            }
            set {
                this.loginEmailField = value;
                this.RaisePropertyChanged("LoginEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int TitleId {
            get {
                return this.titleIdField;
            }
            set {
                this.titleIdField = value;
                this.RaisePropertyChanged("TitleId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Initials {
            get {
                return this.initialsField;
            }
            set {
                this.initialsField = value;
                this.RaisePropertyChanged("Initials");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("Surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string NationalId1 {
            get {
                return this.nationalId1Field;
            }
            set {
                this.nationalId1Field = value;
                this.RaisePropertyChanged("NationalId1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string NationalId2 {
            get {
                return this.nationalId2Field;
            }
            set {
                this.nationalId2Field = value;
                this.RaisePropertyChanged("NationalId2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string NationalId3 {
            get {
                return this.nationalId3Field;
            }
            set {
                this.nationalId3Field = value;
                this.RaisePropertyChanged("NationalId3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int CompanyId {
            get {
                return this.companyIdField;
            }
            set {
                this.companyIdField = value;
                this.RaisePropertyChanged("CompanyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
                this.RaisePropertyChanged("Department");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
                this.RaisePropertyChanged("Address1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
                this.RaisePropertyChanged("Address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Address3 {
            get {
                return this.address3Field;
            }
            set {
                this.address3Field = value;
                this.RaisePropertyChanged("Address3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Address4 {
            get {
                return this.address4Field;
            }
            set {
                this.address4Field = value;
                this.RaisePropertyChanged("Address4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Address5 {
            get {
                return this.address5Field;
            }
            set {
                this.address5Field = value;
                this.RaisePropertyChanged("Address5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public AddressType AddressType {
            get {
                return this.addressTypeField;
            }
            set {
                this.addressTypeField = value;
                this.RaisePropertyChanged("AddressType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int PostAddressId {
            get {
                return this.postAddressIdField;
            }
            set {
                this.postAddressIdField = value;
                this.RaisePropertyChanged("PostAddressId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int PhysicalAddressId {
            get {
                return this.physicalAddressIdField;
            }
            set {
                this.physicalAddressIdField = value;
                this.RaisePropertyChanged("PhysicalAddressId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int CountryId {
            get {
                return this.countryIdField;
            }
            set {
                this.countryIdField = value;
                this.RaisePropertyChanged("CountryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("PhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string CellPhoneNumber {
            get {
                return this.cellPhoneNumberField;
            }
            set {
                this.cellPhoneNumberField = value;
                this.RaisePropertyChanged("CellPhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string FaxPhoneNumber {
            get {
                return this.faxPhoneNumberField;
            }
            set {
                this.faxPhoneNumberField = value;
                this.RaisePropertyChanged("FaxPhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
                this.RaisePropertyChanged("EmailAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string InvoiceEmail {
            get {
                return this.invoiceEmailField;
            }
            set {
                this.invoiceEmailField = value;
                this.RaisePropertyChanged("InvoiceEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string StatementEmail {
            get {
                return this.statementEmailField;
            }
            set {
                this.statementEmailField = value;
                this.RaisePropertyChanged("StatementEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public int Correspondence2 {
            get {
                return this.correspondence2Field;
            }
            set {
                this.correspondence2Field = value;
                this.RaisePropertyChanged("Correspondence2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public decimal Liability {
            get {
                return this.liabilityField;
            }
            set {
                this.liabilityField = value;
                this.RaisePropertyChanged("Liability");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public System.Nullable<System.DateTime> VerificationDate {
            get {
                return this.verificationDateField;
            }
            set {
                this.verificationDateField = value;
                this.RaisePropertyChanged("VerificationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public CustomerStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string CouncilNumber {
            get {
                return this.councilNumberField;
            }
            set {
                this.councilNumberField = value;
                this.RaisePropertyChanged("CouncilNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string PracticeNumber1 {
            get {
                return this.practiceNumber1Field;
            }
            set {
                this.practiceNumber1Field = value;
                this.RaisePropertyChanged("PracticeNumber1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string PracticeNumber2 {
            get {
                return this.practiceNumber2Field;
            }
            set {
                this.practiceNumber2Field = value;
                this.RaisePropertyChanged("PracticeNumber2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string PracticeNumber3 {
            get {
                return this.practiceNumber3Field;
            }
            set {
                this.practiceNumber3Field = value;
                this.RaisePropertyChanged("PracticeNumber3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
                this.RaisePropertyChanged("ModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public int CheckpointPaymentTransactionId {
            get {
                return this.checkpointPaymentTransactionIdField;
            }
            set {
                this.checkpointPaymentTransactionIdField = value;
                this.RaisePropertyChanged("CheckpointPaymentTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public System.DateTime CheckpointPaymentDate {
            get {
                return this.checkpointPaymentDateField;
            }
            set {
                this.checkpointPaymentDateField = value;
                this.RaisePropertyChanged("CheckpointPaymentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public decimal CheckpointPaymentValue {
            get {
                return this.checkpointPaymentValueField;
            }
            set {
                this.checkpointPaymentValueField = value;
                this.RaisePropertyChanged("CheckpointPaymentValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public System.DateTime CheckpointInvoiceDate {
            get {
                return this.checkpointInvoiceDateField;
            }
            set {
                this.checkpointInvoiceDateField = value;
                this.RaisePropertyChanged("CheckpointInvoiceDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public System.DateTime ModifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                this.modifiedOnField = value;
                this.RaisePropertyChanged("ModifiedOn");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum AddressType {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        International,
        
        /// <remarks/>
        PostBox,
        
        /// <remarks/>
        PostStreet,
        
        /// <remarks/>
        UnAssigned,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum CustomerStatus {
        
        /// <remarks/>
        Active,
        
        /// <remarks/>
        Cancelled,
        
        /// <remarks/>
        Dormant,
        
        /// <remarks/>
        Unknown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthorizationResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int yearField;
        
        private int monthField;
        
        private int customerIdField;
        
        private int productIdField;
        
        private int seatsField;
        
        private System.DateTime expirationDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("Year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
                this.RaisePropertyChanged("Month");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("CustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("ProductId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Seats {
            get {
                return this.seatsField;
            }
            set {
                this.seatsField = value;
                this.RaisePropertyChanged("Seats");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("ExpirationDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SeatResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int seatsField;
        
        private string reasonField;
        
        private System.DateTime expirationDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Seats {
            get {
                return this.seatsField;
            }
            set {
                this.seatsField = value;
                this.RaisePropertyChanged("Seats");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("Reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("ExpirationDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Authorize", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthorizeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int pProductId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int pReceiverId;
        
        public AuthorizeRequest() {
        }
        
        public AuthorizeRequest(Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader, int pProductId, int pReceiverId) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.pProductId = pProductId;
            this.pReceiverId = pReceiverId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthorizeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthorizeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Subs.XMLServiceTest.ServiceReference1.SeatResult AuthorizeResult;
        
        public AuthorizeResponse() {
        }
        
        public AuthorizeResponse(Subs.XMLServiceTest.ServiceReference1.SeatResult AuthorizeResult) {
            this.AuthorizeResult = AuthorizeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Authorizations", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthorizationsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader;
        
        public AuthorizationsRequest() {
        }
        
        public AuthorizationsRequest(Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader) {
            this.AuthorizationHeader = AuthorizationHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthorizationsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthorizationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationResult[] AuthorizationsResult;
        
        public AuthorizationsResponse() {
        }
        
        public AuthorizationsResponse(Subs.XMLServiceTest.ServiceReference1.AuthorizationResult[] AuthorizationsResult) {
            this.AuthorizationsResult = AuthorizationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindEMailByCustomerId", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindEMailByCustomerIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int pCustomerId;
        
        public FindEMailByCustomerIdRequest() {
        }
        
        public FindEMailByCustomerIdRequest(Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader, int pCustomerId) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.pCustomerId = pCustomerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindEMailByCustomerIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindEMailByCustomerIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool FindEMailByCustomerIdResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pEmailAddress;
        
        public FindEMailByCustomerIdResponse() {
        }
        
        public FindEMailByCustomerIdResponse(bool FindEMailByCustomerIdResult, string pEmailAddress) {
            this.FindEMailByCustomerIdResult = FindEMailByCustomerIdResult;
            this.pEmailAddress = pEmailAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindCustomerIdByEmail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindCustomerIdByEmailRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string EmailAddress;
        
        public FindCustomerIdByEmailRequest() {
        }
        
        public FindCustomerIdByEmailRequest(Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader, string EmailAddress) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.EmailAddress = EmailAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindCustomerIdByEmailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindCustomerIdByEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool FindCustomerIdByEmailResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int CustomerId;
        
        public FindCustomerIdByEmailResponse() {
        }
        
        public FindCustomerIdByEmailResponse(bool FindCustomerIdByEmailResult, int CustomerId) {
            this.FindCustomerIdByEmailResult = FindCustomerIdByEmailResult;
            this.CustomerId = CustomerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindCustomerIdByNationalId", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindCustomerIdByNationalIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string NationalId;
        
        public FindCustomerIdByNationalIdRequest() {
        }
        
        public FindCustomerIdByNationalIdRequest(Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader, string NationalId) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.NationalId = NationalId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindCustomerIdByNationalIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindCustomerIdByNationalIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool FindCustomerIdByNationalIdResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int CustomerId;
        
        public FindCustomerIdByNationalIdResponse() {
        }
        
        public FindCustomerIdByNationalIdResponse(bool FindCustomerIdByNationalIdResult, int CustomerId) {
            this.FindCustomerIdByNationalIdResult = FindCustomerIdByNationalIdResult;
            this.CustomerId = CustomerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertCustomer", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertCustomerRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Subs.XMLServiceTest.ServiceReference1.CustomerData3 pCustomerData;
        
        public InsertCustomerRequest() {
        }
        
        public InsertCustomerRequest(Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader, Subs.XMLServiceTest.ServiceReference1.CustomerData3 pCustomerData) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.pCustomerData = pCustomerData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertCustomerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string InsertCustomerResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Subs.XMLServiceTest.ServiceReference1.CustomerData3 pCustomerData;
        
        public InsertCustomerResponse() {
        }
        
        public InsertCustomerResponse(string InsertCustomerResult, Subs.XMLServiceTest.ServiceReference1.CustomerData3 pCustomerData) {
            this.InsertCustomerResult = InsertCustomerResult;
            this.pCustomerData = pCustomerData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomer", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomerRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pLoginEmail;
        
        public GetCustomerRequest() {
        }
        
        public GetCustomerRequest(Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader, string pLoginEmail) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.pLoginEmail = pLoginEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetCustomerResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Subs.XMLServiceTest.ServiceReference1.CustomerData3 pCustomerData;
        
        public GetCustomerResponse() {
        }
        
        public GetCustomerResponse(string GetCustomerResult, Subs.XMLServiceTest.ServiceReference1.CustomerData3 pCustomerData) {
            this.GetCustomerResult = GetCustomerResult;
            this.pCustomerData = pCustomerData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCustomer", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateCustomerRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Subs.XMLServiceTest.ServiceReference1.CustomerData3 pCustomerData;
        
        public UpdateCustomerRequest() {
        }
        
        public UpdateCustomerRequest(Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader, Subs.XMLServiceTest.ServiceReference1.CustomerData3 pCustomerData) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.pCustomerData = pCustomerData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCustomerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UpdateCustomerResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Subs.XMLServiceTest.ServiceReference1.CustomerData3 pCustomerData;
        
        public UpdateCustomerResponse() {
        }
        
        public UpdateCustomerResponse(string UpdateCustomerResult, Subs.XMLServiceTest.ServiceReference1.CustomerData3 pCustomerData) {
            this.UpdateCustomerResult = UpdateCustomerResult;
            this.pCustomerData = pCustomerData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertDeliveryAddress", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertDeliveryAddressRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Subs.XMLServiceTest.ServiceReference1.DeliveryAddressData2 pDeliveryAddressData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int pCustomerId;
        
        public InsertDeliveryAddressRequest() {
        }
        
        public InsertDeliveryAddressRequest(Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader, Subs.XMLServiceTest.ServiceReference1.DeliveryAddressData2 pDeliveryAddressData, int pCustomerId) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.pDeliveryAddressData = pDeliveryAddressData;
            this.pCustomerId = pCustomerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertDeliveryAddressResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertDeliveryAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string InsertDeliveryAddressResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Subs.XMLServiceTest.ServiceReference1.DeliveryAddressData2 pDeliveryAddressData;
        
        public InsertDeliveryAddressResponse() {
        }
        
        public InsertDeliveryAddressResponse(string InsertDeliveryAddressResult, Subs.XMLServiceTest.ServiceReference1.DeliveryAddressData2 pDeliveryAddressData) {
            this.InsertDeliveryAddressResult = InsertDeliveryAddressResult;
            this.pDeliveryAddressData = pDeliveryAddressData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDeliveryAddress", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDeliveryAddressRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int pDeliveryAddressId;
        
        public GetDeliveryAddressRequest() {
        }
        
        public GetDeliveryAddressRequest(Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader, int pDeliveryAddressId) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.pDeliveryAddressId = pDeliveryAddressId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDeliveryAddressResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDeliveryAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetDeliveryAddressResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Subs.XMLServiceTest.ServiceReference1.DeliveryAddressData2 pDeliveryAddressData;
        
        public GetDeliveryAddressResponse() {
        }
        
        public GetDeliveryAddressResponse(string GetDeliveryAddressResult, Subs.XMLServiceTest.ServiceReference1.DeliveryAddressData2 pDeliveryAddressData) {
            this.GetDeliveryAddressResult = GetDeliveryAddressResult;
            this.pDeliveryAddressData = pDeliveryAddressData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDeliveryAddress", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateDeliveryAddressRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Subs.XMLServiceTest.ServiceReference1.DeliveryAddressData2 pDeliveryAddressData;
        
        public UpdateDeliveryAddressRequest() {
        }
        
        public UpdateDeliveryAddressRequest(Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader, Subs.XMLServiceTest.ServiceReference1.DeliveryAddressData2 pDeliveryAddressData) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.pDeliveryAddressData = pDeliveryAddressData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDeliveryAddressResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateDeliveryAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UpdateDeliveryAddressResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Subs.XMLServiceTest.ServiceReference1.DeliveryAddressData2 pDeliveryAddressData;
        
        public UpdateDeliveryAddressResponse() {
        }
        
        public UpdateDeliveryAddressResponse(string UpdateDeliveryAddressResult, Subs.XMLServiceTest.ServiceReference1.DeliveryAddressData2 pDeliveryAddressData) {
            this.UpdateDeliveryAddressResult = UpdateDeliveryAddressResult;
            this.pDeliveryAddressData = pDeliveryAddressData;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Subs.XMLServiceTest.ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Subs.XMLServiceTest.ServiceReference1.ServiceSoap>, Subs.XMLServiceTest.ServiceReference1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Subs.XMLServiceTest.ServiceReference1.AuthorizeResponse Authorize(Subs.XMLServiceTest.ServiceReference1.AuthorizeRequest request) {
            return base.Channel.Authorize(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.AuthorizeResponse> AuthorizeAsync(Subs.XMLServiceTest.ServiceReference1.AuthorizeRequest request) {
            return base.Channel.AuthorizeAsync(request);
        }
        
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationsResponse Authorizations(Subs.XMLServiceTest.ServiceReference1.AuthorizationsRequest request) {
            return base.Channel.Authorizations(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.AuthorizationsResponse> AuthorizationsAsync(Subs.XMLServiceTest.ServiceReference1.AuthorizationsRequest request) {
            return base.Channel.AuthorizationsAsync(request);
        }
        
        public Subs.XMLServiceTest.ServiceReference1.FindEMailByCustomerIdResponse FindEMailByCustomerId(Subs.XMLServiceTest.ServiceReference1.FindEMailByCustomerIdRequest request) {
            return base.Channel.FindEMailByCustomerId(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.FindEMailByCustomerIdResponse> FindEMailByCustomerIdAsync(Subs.XMLServiceTest.ServiceReference1.FindEMailByCustomerIdRequest request) {
            return base.Channel.FindEMailByCustomerIdAsync(request);
        }
        
        public Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByEmailResponse FindCustomerIdByEmail(Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByEmailRequest request) {
            return base.Channel.FindCustomerIdByEmail(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByEmailResponse> FindCustomerIdByEmailAsync(Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByEmailRequest request) {
            return base.Channel.FindCustomerIdByEmailAsync(request);
        }
        
        public Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByNationalIdResponse FindCustomerIdByNationalId(Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByNationalIdRequest request) {
            return base.Channel.FindCustomerIdByNationalId(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByNationalIdResponse> FindCustomerIdByNationalIdAsync(Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByNationalIdRequest request) {
            return base.Channel.FindCustomerIdByNationalIdAsync(request);
        }
        
        public Subs.XMLServiceTest.ServiceReference1.InsertCustomerResponse InsertCustomer(Subs.XMLServiceTest.ServiceReference1.InsertCustomerRequest request) {
            return base.Channel.InsertCustomer(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.InsertCustomerResponse> InsertCustomerAsync(Subs.XMLServiceTest.ServiceReference1.InsertCustomerRequest request) {
            return base.Channel.InsertCustomerAsync(request);
        }
        
        public Subs.XMLServiceTest.ServiceReference1.GetCustomerResponse GetCustomer(Subs.XMLServiceTest.ServiceReference1.GetCustomerRequest request) {
            return base.Channel.GetCustomer(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.GetCustomerResponse> GetCustomerAsync(Subs.XMLServiceTest.ServiceReference1.GetCustomerRequest request) {
            return base.Channel.GetCustomerAsync(request);
        }
        
        public Subs.XMLServiceTest.ServiceReference1.UpdateCustomerResponse UpdateCustomer(Subs.XMLServiceTest.ServiceReference1.UpdateCustomerRequest request) {
            return base.Channel.UpdateCustomer(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.UpdateCustomerResponse> UpdateCustomerAsync(Subs.XMLServiceTest.ServiceReference1.UpdateCustomerRequest request) {
            return base.Channel.UpdateCustomerAsync(request);
        }
        
        public Subs.XMLServiceTest.ServiceReference1.InsertDeliveryAddressResponse InsertDeliveryAddress(Subs.XMLServiceTest.ServiceReference1.InsertDeliveryAddressRequest request) {
            return base.Channel.InsertDeliveryAddress(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.InsertDeliveryAddressResponse> InsertDeliveryAddressAsync(Subs.XMLServiceTest.ServiceReference1.InsertDeliveryAddressRequest request) {
            return base.Channel.InsertDeliveryAddressAsync(request);
        }
        
        public Subs.XMLServiceTest.ServiceReference1.GetDeliveryAddressResponse GetDeliveryAddress(Subs.XMLServiceTest.ServiceReference1.GetDeliveryAddressRequest request) {
            return base.Channel.GetDeliveryAddress(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.GetDeliveryAddressResponse> GetDeliveryAddressAsync(Subs.XMLServiceTest.ServiceReference1.GetDeliveryAddressRequest request) {
            return base.Channel.GetDeliveryAddressAsync(request);
        }
        
        public Subs.XMLServiceTest.ServiceReference1.UpdateDeliveryAddressResponse UpdateDeliveryAddress(Subs.XMLServiceTest.ServiceReference1.UpdateDeliveryAddressRequest request) {
            return base.Channel.UpdateDeliveryAddress(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.UpdateDeliveryAddressResponse> UpdateDeliveryAddressAsync(Subs.XMLServiceTest.ServiceReference1.UpdateDeliveryAddressRequest request) {
            return base.Channel.UpdateDeliveryAddressAsync(request);
        }
    }
}
